#!/bin/bash

# Script to display Day as Dot
# Closebox73

DATE=$(date +"%a")

if [[ "${DATE}" = *Mon* ]]; then
    echo "      "
elif [[ "${DATE}" = *Tue* ]]; then
    echo "      "
elif [[ "${DATE}" = *Wed* ]]; then
    echo "      "
elif [[ "${DATE}" = *Thu* ]]; then
    echo "      "
elif [[ "${DATE}" = *Fri* ]]; then
    echo "      "
elif [[ "${DATE}" = *Sat* ]]; then
	echo "      "
elif [[ "${DATE}" = *Sun* ]]; then
    echo "      "
else
	echo "There are other day??"
fi

exit
