## ░█▀▀░▀█▀░█▀█░█▀▄░█▀▀░█░█░▀█▀░█▀█
## ░▀▀█░░█░░█▀█░█▀▄░▀▀█░█▀█░░█░░█▀▀
## ░▀▀▀░░▀░░▀░▀░▀░▀░▀▀▀░▀░▀░▀▀▀░▀░░
# Setups

format="""$directory$git_branch$time\
[](fg:#1b0d2b)\
$c\
$python\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[ ](fg:#1b0d2b)\
$character
"""
# right_format = """$git_status$cmd_duration"""
add_newline = true


[c]
symbol = ""
style = "bg:#1b0d2b fg:#ffffff"
format = '[$symbol]($style)'

[python]
symbol = "🐍"
style = "bg:#1b0d2b fg:#ffffff"
format = '[$symbol]($style)'

[java]
symbol = ""
style = "bg:#1b0d2b"
format = '[$symbol]($style)'

[conda]
format = ' [$symbol$environment](dimmed green) '

# Prompt symbols 
[character]
success_symbol = "[](#ffffff bold)"
error_symbol = "[](#d43981) "
vicmd_symbol = "[](#DD8F6E) "

[directory]
format = " []($style)[$path](bg:#111f3b fg:#8d9aa1 )[ ]($style)"
style = "bg:none fg:#111f3b"
truncation_length = 3
truncate_to_repo=false

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
format = "[]($style)[[  ](bg:#B075A8 fg:#005912 bold)$branch](bg:#B075A8 fg:#005912)[ ]($style)"
style = "bg:none fg:#B075A8"

[git_status]
# $all status$ahead_behind
format = "[]($style)[$all_status$ahead_behind](bg:#312C2E fg:#b4befe)[ ]($style)"
style = "bg:none fg:#312C2E"
conflicted = "="
ahead =	"⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
up_to_date = ""
untracked = "?${count}"
stashed = ""
modified = "!${count}"
staged = "+${count}"
renamed = "»${count}"
deleted = "${count}"

[cmd_duration]
min_time = 1
# duration & style 
format = "[]($style)[[神](bg:#cccccc fg:#821b3a bold)$duration](bg:#cccccc fg:#121210)[ ]($style)"
disabled = false
style = "bg:none fg:#cccccc"

[elixir]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'


[julia]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'


[nim]
symbol = "󰆥 "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'


[scala]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%I:%M %p" # Hour:Minute Format
style = "bg:none fg:#C7714F"
format = "[]($style)[[ ](bg:#C7714F fg:#0b1f10 bold)$time](bg:#C7714F fg:#0b1f10)[ ]($style)"


