console_title_template = '{{ .Folder }}'
version = 3

[transient_prompt]
  foreground_templates = [
    "{{if gt .Code 0}}#f38ba8{{end}}",
    "{{if eq .Code 0}}#cba6f7{{end}}",
  ]
  background = 'transparent'
  template = '{{ .UserName }}@{{ .HostName }} ❯ '

[upgrade]
  source = 'cdn'
  interval = '168h'
  auto = false
  notice = false

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    leading_diamond = '<#cba6f7> </> '
    template = '{{ .UserName }} @ {{ .HostName }}'
    foreground = '#bac2de'
    type = 'session'
    style = 'diamond'

    [blocks.segments.properties]
      display_host = true

  [[blocks.segments]]
    template = '<#f5e0dc>{{ .UpstreamIcon }}</>{{ .HEAD }}{{if .BranchStatus}} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }} <#eba0ac> {{ .Working.String }}</>{{ end }}{{ if .Staging.Changed }} <#a6e3a1> {{ .Staging.String }}</>{{ end }}'
    foreground = '#f5c2e7'
    type = 'git'
    style = 'diamond'

    [blocks.segments.properties]
      branch_icon = ' '
      fetch_status = true
      fetch_upstream_icon = true
      fetch_worktree_count = true

[[blocks]]
  type = 'prompt'
  alignment = 'right'

  [[blocks.segments]]
    foreground = '#cdd6f4'
    type = 'text'
    style = 'plain'

  [[blocks.segments]]
    template = ' <#f2cdcd>{{ .FormattedMs }}s</> <#94e2d5>󰇝</>'
    foreground = '#cdd6f4'
    type = 'executiontime'
    style = 'diamond'

    [blocks.segments.properties]
      style = 'dallas'
      threshold = 1000

  [[blocks.segments]]
    template = ' {{ .CurrentDate | date .Format }} '
    foreground = '#b4befe'
    type = 'time'
    style = 'diamond'

    [blocks.segments.properties]
      time_format = 'Monday <#f2cdcd>at</> 3:04 PM'

  [[blocks.segments]]
    template = ' '
    foreground = '#f38ba8'
    type = 'root'
    style = 'diamond'

    [blocks.segments.properties]
      root_icon = ' '

  [[blocks.segments]]
    template = ' <#94e2d5></> {{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }} '
    foreground = '#a6adc8'
    type = 'node'
    style = 'diamond'

  [[blocks.segments]]
    template = ' <#74c7ec></> {{ .Full }} '
    foreground = '#a6adc8'
    type = 'python'
    style = 'diamond'

  [[blocks.segments]]
    template = ' <#89b4fa></> {{ .Full }} '
    foreground = '#a6adc8'
    type = 'go'
    style = 'diamond'

  # [[blocks.segments]]
    # template = ' <#cdd6f4>󰍛</> {{ round .PhysicalPercentUsed .Precision }}% ({{ (div ((sub .PhysicalTotalMemory .PhysicalAvailableMemory)|float64) 1073741824.0) }}/{{ (div .PhysicalTotalMemory 1073741824.0) }}) GB'
    # foreground = '#bac2de'
    # type = 'sysinfo'
    # style = 'diamond'

    # [blocks.segments.properties]
      # precision = 0


[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '  {{ .Path }}'
    foreground = '#89b4fa'
    type = 'path'
    style = 'diamond'

    [blocks.segments.properties]
      folder_icon = '/'
      folder_separator_icon = ' / '
      home_icon = 'home'
      style = 'agnoster_full'

  [[blocks.segments]]
    template = ' ❯ '
    foreground = '#cba6f7'
    type = 'status'
    style = 'plain'
    foreground_templates = ['{{ if gt .Code 0 }}#f38ba8{{ end }}']

    [blocks.segments.properties]
      always_enabled = true
