# vim:ft=kitty

# ==============================================================================
# Theme
# ==============================================================================
include ./current-theme.conf

# ==============================================================================
# Fonts
# ==============================================================================
font_family      family="Agave Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        12.5

# ==============================================================================
# Window & Layout
# ==============================================================================
remember_window_size  yes
initial_window_width  120c
initial_window_height 34c
window_padding_width  14
enabled_layouts       splits, tall, stack

# ==============================================================================
# Tabs
# ==============================================================================
tab_bar_edge          bottom
tab_bar_style         powerline
tab_powerline_style   round
tab_bar_min_tabs      2
active_tab_font_style bold
inactive_tab_font_style normal
tab_title_max_length  24
tab_activity_symbol   "•"
tab_title_template    " {index} {title[:18]}{' :{}:'.format(num_windows) if num_windows > 1 else ''} "
active_tab_title_template "{fmt.bold} {index} {title[:18]}{' :{}:'.format(num_windows) if num_windows > 1 else ''} "

# ==============================================================================
# Cursor & Interaction
# ==============================================================================
cursor_shape                     beam
cursor_trail                     2
mouse_hide_wait                  1.0
strip_trailing_spaces            smart
confirm_os_window_close          0
enable_audio_bell                no
visual_bell_duration             0.0

# ==============================================================================
# Transparency
# ==============================================================================
dynamic_background_opacity yes
background_opacity         0.92

# ==============================================================================
# Remote control
# ==============================================================================
allow_remote_control yes
listen_on unix:@mykitty

# ==============================================================================
# Keymaps
# ==============================================================================
map ctrl+shift+a>m set_background_opacity +0.1
map ctrl+shift+a>l set_background_opacity -0.1
map ctrl+shift+e   kitten hints
