#!/bin/bash

down() {
pamixer -d 5 --allow-boost --set-limit 150
volume=$(pamixer --get-volume)
[$volume -gt 0 ] && volume=`expr $volume`  
mpv $HOME/.sounds/attaboy_01.ogg &
}

up() {
pamixer -i 5 --allow-boost --set-limit 150
volume=$(pamixer --get-volume)
[ $volume -lt 150 ] && volume=`expr $volume`  
mpv $HOME/.sounds/attaboy_01.ogg &
}

mute() {
muted="$(pamixer --get-mute)"
if $muted; then
  pamixer -u
else 
  pamixer -m
fi
}

case "$1" in
  up) up;;
  down) down;;
  mute) mute;;
esac
