#!/bin/bash

down() {
pamixer -d 5 --allow-boost --set-limit 150
mpv $HOME/.sounds/attaboy_01.ogg &
}

up() {
pamixer -i 5 --allow-boost --set-limit 150
mpv $HOME/.sounds/attaboy_01.ogg &
}

mute() {
muted="$(pamixer --get-mute)"
if $muted; then
  pamixer -u
else 
  pamixer -m
fi
}

case "$1" in
  up) up;;
  down) down;;
  mute) mute;;
esac
